name: Python application test with Github Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Type checking with Mypy
      run: |
        mypy --ignore-missing-imports .

    - name: Run unit tests
      run: |
        python -m unittest discover -s unit_tests

    - name: Measure Performance
      run: |
        python Initial_data_load_db.py

    - name: Analyze with Pylint
      run: |
        pylint **/*.py

    - name: Generate PEP 8 Compliance Report
      run: |
        pycodestyle --first **/*.py